### PR TITLE
Fix ISIS-1615

### PR DESCRIPTION
**Pull request by hobrom**
https://issues.apache.org/jira/browse/ISIS-1615

### CODE REVIEW

**Comment by danhaywood** [comment]
I'm currently working on a branch - about to merge into master - that I think will conflict with this.  I'll try out this patch though, let you know if it works.  If so, then will need you to rebase this PR.

**Comment by hobrom** [comment]
ok, thanks!

**Comment by danhaywood** [comment]
OK, so yes, this PR seems to be compatible.  I'll ping later when merged my current branch into master.

**Comment by hobrom** [comment]
When testing this fix, I discovered another issue. Don't know if related or not:

Click on the action button (that as the confirm dialog) and cancel the dialog. Then the immediate next click on the button will not fire a click event. Click again and the confirmation dialog pops up again as intended.

**Comment by danhaywood** [comment]
Thanks for the commit, Andi.

If you have the time, checkout promptStyle="INLINE" for actions and property edits.  Also, try the "isis.viewer.wicket.redirectEvenIfSameObject", set to false by default so reuse the same page if possible, or true to reinstate pre-1.15.0 behaviour.

**Comment by hobrom** [comment]
Thanks! Can't wait to switch to 1.15 once released! ;)

**Comment by danhaywood** [comment]
are you interested in coming to "IsisCon" in Amsterdam, by the way?  I think in total there are 10 of us, with 5 non-committers.  But perhaps you are busy?

**Comment by hobrom** [comment]
Sounds very interesting, wish I had a sponsor. ;) Anyway, thanks for the invite!

**Pull request merged**
