### PR TITLE
ISIS-2209: fix broken contributing link

### PR DESCRIPTION
**Pull request by HeVictor**
This fixes the broken contribution info link for Apache Isis.

### CODE REVIEW

**Comment by andi-huber** [comment]
Thanks for spotting that. As this is a built site (using antora) I believe the link should be rather some generic `xref: ...` reference, that antora autoresolves. In other words we should not need site internal static links of sort `https://isis.apache.org/conguide/version-xxx/contributing.html`

**Comment by danhaywood** [comment]
Actually, we are on M8 now, so the patch isn't quite correct.

**Comment by andi-huber** [comment]
@HeVictor could you update the link to 'M8', then I'm happy to merge.

**Comment by HeVictor** [comment]
@andi-huber Apologies for the late response but I wasn't able to get back to this until now, but I see you've made the required change already which is great. Thanks for taking care of it.

**Comment by andi-huber** [comment]
No worries. Thanks for your contribution regardless.

**Pull request closed without merging**
