### PR TITLE
ISIS-471: Pinnable (for session) bookmarks

### PR DESCRIPTION
**Pull request by jmhupanen**

### CODE REVIEW

**Comment by andi-huber** [comment]
Cool stuff, thanks a lot!

**Comment by andi-huber** [comment]
Hi @jmhupanen - I tried my best for over an hour, could not get it working. I now moved this stuff into a branch and reverted the merge to 'master'. If you like you can pick it up again and file a PR against https://github.com/apache/isis/tree/ISIS-471-pin.bookmark

However, I feel we might also regard this one as a **won't fix**, since our focus for the remaining year will be to conquer new territory with the _Vaadin Viewer_.

Let me know what you think.

**Comment by jmhupanen** [comment]
@andi-huber Ok, that's fine. I'll look into that at some point, if I have time, and file a PR if I can find a fix.

**Comment by andi-huber** [comment]
Just to clarify what I meant: maybe we can just close this issue (ISIS-471) as a **won't fix**. Unless you care and want it fixed.

**Comment by andi-huber** [comment]
Also I must admit, I don't know this feature very well. I don't even know what this issue (ISIS-471) is about. Bookmarks should be kept throughout a user session anyway, why pining?

**Comment by jmhupanen** [comment]
Yes, I think this can closed as a **wont't fix**. As I understand it, the reason for pinning the bookmarks is to prevent them from being removed from the bookmarks list by automatic cleaning algorithm. My intention was to implement it by ignoring the pinned bookmarks so that they are not counted as removable bookmarks by the algorithm.

**Comment by danhaywood** [comment]
Hi Juho,
if you feel like you'd like to contribute to the framework further, then
join our slack channel and have a discussion first with us first as to what
you'd like to work on.
Thx
Dan

**Pull request merged**
