### PR TITLE
Finish sentence

### PR DESCRIPTION
**Pull request by bradh**
Lots of things could go in here. I also considered "...from an item that is not yet overdue"

### CODE REVIEW

**Comment by andi-huber** [comment]
how about this:
"... or an overdue `Loan` might be distinguished from one that is fully paid."

**Comment by andi-huber** [comment]
Ok, so why not ...
"or a library book that is `loaned out` might be distinguished from one that is `available`."

Do you want me to wait for you to update this PR, or shall I do a separate commit?

**Comment by bradh** [comment]
Happy for you do do it.

**Comment by andi-huber** [comment]
changes committed to `master`

Thanks for the contributions Brad!

**Pull request closed without merging**
