### PR TITLE
ISIS-1985: fixes mm validation

### PR DESCRIPTION
**Pull request by andi-huber**
Task-Url: https://issues.apache.org/jira/browse/ISIS-1985

### CODE REVIEW

**Comment by andi-huber** [comment]
this PR backports fixes from v2

**Comment by andi-huber** [comment]
Hi Dan, what's up, why did you close this one? It's not filed against 'master'!

**Comment by danhaywood** [comment]
Hi Andi

I didn't close it, but I did just switch the branches around (see mail on
dev@) which involved a force push to master.  So maybe github closed the PR
because its target branch was changed?

Perhaps you can resurrect it somehow?

Thx
Dan

PS: you didn't raise a new PR for the OA stuff, did you?  If so, maybe that
was also auto-closed?

**Comment by andi-huber** [comment]
Ah, that's why. I'll reopen. Thx

**Pull request closed without merging**
